service: aws-api-gw-authorizers

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x
  httpApi:
    authorizers:
      firstAuthorizer:
        type: request
        functionName: authorizer-first
      secondAuthorizer:
        type: request
        functionName: authorizer-second

functions:
  authorizer-first:
    environment:
      API_KEY: ${ssm:/app/apikey/first}
    handler: lambda/authorizer-first.handler

  authorizer-second:
    environment:
      API_KEY: ${ssm:/app/apikey/second}
    handler: lambda/authorizer-second.handler

  first:
    handler: lambda/first.handler
    events:
      - httpApi:
          path: /first
          method: get
          authorizer:
            name: firstAuthorizer

  second:
    handler: lambda/second.handler
    events:
      - httpApi:
          path: /second
          method: get
          authorizer:
            name: secondAuthorizer
